name: CreateEnv

on:
  repository_dispatch:
    typse: [hoge]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: echo
        run: |
          echo "hoge"